### ISSUE TITLE
Error when on a server

### ISSUE THREAD

**Issue by goosewoman** [GeyserMC/MCProtocolLib#15]
http://pastebin.com/iJ1aBmnc

I created my own bot and it connects to the local server just fine, but when I connect mc.ecocitycraft.com it crashes with this stack trace.

**Comment by goosewoman** [comment]
The same error occurs on the latest commit.
The server is running the latest build of spigot, so I'll test that on my local server and see if it's the same problem.

EDIT: It appears to be one of the plugins running on ecocitycraft, not spigot itself.

**Comment by goosewoman** [comment]
That works, somewhat, but I'm getting a completely different error now. http://pastebin.com/y8EpxkSb

My own code is nowhere in this stack trace, so I think it's safe to assume the fault lies in the protocol lib/packetlib

**Comment by goosewoman** [comment]
It works perfectly, thank you very much.

**Comment by goosewoman** [comment]
I found another error that results in a stacktrace/crash (It doesn't seem to happen often)

http://pastebin.com/raw.php?i=2jdqvve0

It crashes whenever someone's breaking a block.

**Comment by goosewoman** [comment]
Sometimes in busy areas my bot disconnects with the reason

Disconnected: Internal exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: 11

sometimes the value is 12

This isn't from my code, as all my exceptions print stack traces.

**Comment by goosewoman** [comment]
Well, whatever it is.

```
@Override
public void disconnected( DisconnectedEvent event )
{
    System.out.println( "Disconnected: " + new Message( event.getReason(), true ).getRawText() );
}
```

It comes from this code.

**Comment by goosewoman** [comment]
It finally crashed again.

Disconnected: Internal network exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: 11

**Comment by goosewoman** [comment]
Looks like I got a full stack trace this time

Disconnected: Internal network exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: 11
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: 11
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:258)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:140)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:154)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:154)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:148)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
        at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 11
        at ch.spacebase.mc.protocol.packet.ingame.server.world.ServerBlockBreakAnimPacket.read(ServerBlockBreakAnimPacket.java:55)
        at ch.spacebase.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:36)
        at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:227)
        ... 26 more

**Comment by goosewoman** [comment]
Doesn't seem to be happening any more. I'll leave my bot running for a day and see how it goes.

**Comment by minecraftkeba** [comment]
I get the same error while teleporting between two worlds.
