### ISSUE TITLE
Need a way to tell clients to unload chunks.

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#16]
I need to tell the client to unload chunks.  According to http://wiki.vg/Protocol#Chunk_Data I need to set "Ground-Up Continuous" to true and have no chunks present in a Chunk Data packet.  However...when I try to do this I get the following exception:

<code>
java.lang.IllegalArgumentException: Chunks must contain all 16 chunks in a column if biomeData is not null.
    at ch.spacebase.mc.protocol.packet.ingame.server.world.ServerChunkDataPacket.<init>(ServerChunkDataPacket.java:54)
</code>

How should I tell the client to unload chunks?

<i>From  http://wiki.vg/Protocol#Chunk_Data</i>
<b>
Chunk Data
</b>
Chunks are not unloaded by the client automatically. To unload chunks, send this packet with ground-up continuous=true and no 16^3 chunks (eg. primary bit mask=0). The server does not send skylight information for nether-chunks, it's up to the client to know if the player is currently in the nether. You can also infer this information from the primary bitmask and the amount of uncompressed bytes sent.

**Comment by ghost** [comment]
I have pulled in these changes but I'm still not sure how I can send a Chunk Data packet with no chunks but have "Ground-Up Continuous" field set to true.  Can you give me an example on how to use this to send chunk unload packets?

**Comment by ghost** [comment]
I'm running into a NullPointerexception trying that:

``` java
session.send(new ServerChunkDataPacket(new Chunk[16], new byte[256])); 
```

<pre>
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:129)
    at io.netty.handler.codec.ByteToMessageCodec.write(ByteToMessageCodec.java:113)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeWriteNow(ChannelHandlerInvokerUtil.java:140)
    at io.netty.channel.DefaultChannelHandlerInvoker$WriteTask.run(DefaultChannelHandlerInvoker.java:425)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:318)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at java.lang.System.arraycopy(Native Method)
    at ch.spacebase.mc.util.NetUtil.chunksToData(NetUtil.java:296)
    at ch.spacebase.mc.protocol.packet.ingame.server.world.ServerChunkDataPacket.write(ServerChunkDataPacket.java:117)
    at ch.spacebase.packetlib.tcp.TcpPacketCodec.encode(TcpPacketCodec.java:28)
    at ch.spacebase.packetlib.tcp.TcpPacketCodec.encode(TcpPacketCodec.java:16)
    at io.netty.handler.codec.ByteToMessageCodec$Encoder.encode(ByteToMessageCodec.java:145)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:111)
    ... 7 more
</pre>

**Comment by ghost** [comment]
works perfectly, thanks!
