### ISSUE TITLE
Error when sending ChunkData to 1.9.2 Vanilla Client

### ISSUE THREAD

**Issue by Zidane** [GeyserMC/MCProtocolLib#160]
First off, hey @Steveice10 :). Long time no see.

Found this lib, really enjoying your work so far! Ran into a snag:

```
[01:16:29] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: readerIndex(63667) + length(2048) exceeds writerIndex(65632): UnpooledHeapByteBuf(ridx: 63667, widx: 65632, cap: 65632/65632)
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
    at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
    at g.a(SourceFile:46) [1.9.2.jar:?]
    at bcc.av(SourceFile:954) [1.9.2.jar:?]
    at bcc.a(SourceFile:392) [1.9.2.jar:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [1.9.2.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(63667) + length(2048) exceeds writerIndex(65632): UnpooledHeapByteBuf(ridx: 63667, widx: 65632, cap: 65632/65632)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
    at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:676) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
    at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:684) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
    at em.readBytes(SourceFile:784) ~[1.9.2.jar:?]
    at ase.a(SourceFile:911) ~[1.9.2.jar:?]
    at bkp.a(SourceFile:612) ~[1.9.2.jar:?]
    at gp.a(SourceFile:64) ~[1.9.2.jar:?]
    at gp.a(SourceFile:12) ~[1.9.2.jar:?]
    at fh$1.run(SourceFile:13) ~[1.9.2.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
    at g.a(SourceFile:45) ~[1.9.2.jar:?]
    ... 3 more
```

Using the following code:

```
            final Chunk[] chunks = new Chunk[16];

            for (int section = 0; section < 16; section++) {
                final Chunk chunk = new Chunk(false);

                for (int bx = 0; bx < 16; bx++) {
                    for (int bz = 0; bz < bx; bz++) {
                        for (int by = 0; by < bz; by++) {
                            if (new Random().nextBoolean()) {
                                chunk.getBlocks().set(bx, by, bz, new BlockState(1, 0));
                            }
                        }
                    }
                }

                chunks[section] = chunk;
            }

            session.send(new ServerChunkDataPacket(new Column(0, 0, chunks)));
```

I'm fairly new to the lib. Am I missing something?

**Comment by Steveice10** [comment]
Try passing "true" to the Chunk constructor.

**Comment by Zidane** [comment]
@Steveice10 

Thanks for the quick reply. That seemed to work but I don't see my columns on the client. Client still reports it is "Waiting for chunk..." in debug menu. I can paste some testing code I'm doing in login:

```
server.setGlobalFlag(MinecraftConstants.SERVER_LOGIN_HANDLER_KEY, (ServerLoginHandler) session -> {

            final GameProfile profile = session.getFlag(MinecraftConstants.PROFILE_KEY);
            session.send(new ServerJoinGamePacket(0, true, GameMode.SURVIVAL, 0, Difficulty.PEACEFUL, 10, WorldType.DEFAULT, false));
            final ByteBuf buffer = Unpooled.buffer();
            final ByteBufNetOutput adapter = new ByteBufNetOutput(buffer);
            try {
                adapter.writeString("Sponge");
            } catch (IOException e) {
                SpongeGame.logger.error(e.toString());
            }
            session.send(new ServerPluginMessagePacket("MC|Brand", buffer.array()));
            session.send(new ServerSpawnPositionPacket(new Position(0, 64, 0)));
            session.send(new ServerPlayerAbilitiesPacket(false, false, false, true, 0.05f, 0.1f));
            session.send(new ServerPlayerPositionRotationPacket(0, 64, 0, 0, 0, 0));
            for (Session activeSession : sessions) {
                activeSession.send(new ServerPlayerListEntryPacket(PlayerListEntryAction.ADD_PLAYER, new PlayerListEntry[]{new PlayerListEntry(profile,
                        GameMode.CREATIVE, 10, new TextMessage(profile.getName()))}));

                if (activeSession != session) {
                    final GameProfile otherProfile = activeSession.getFlag(MinecraftConstants.PROFILE_KEY);
                    session.send(new ServerPlayerListEntryPacket(PlayerListEntryAction.ADD_PLAYER, new PlayerListEntry[]{new PlayerListEntry(otherProfile,
                            GameMode.CREATIVE, 10, new TextMessage(otherProfile.getName()))}));
                }

                activeSession.send(new ServerChatPacket(profile.getName() + " has joined the game."));
            }


            final Chunk[] chunks = new Chunk[16];
            final BlockState state = new BlockState(1, 0);
            for (int section = 0; section < 16; section++) {
                final Chunk chunk = new Chunk(true);

                for (int bx = 0; bx < 16; bx++) {
                    for (int bz = 0; bz < bx; bz++) {
                        for (int by = 0; by < 16; by++) {
                            if (new Random().nextBoolean()) {
                                chunk.getBlocks().set(bx, by, bz, state);
                            }
                        }
                    }
                }

                chunks[section] = chunk;
            }
```

**Comment by Steveice10** [comment]
Ah, try passing a byte array (can be zeroes) to the Column constructor for the optional biome data parameter. In the protocol, a column is sent with biome data when it's the full Chunk, and without when merely updating parts of the Chunk. I believe the problem is that the client expects to initially receive full chunks.

**Comment by Zidane** [comment]
@Steveice10 

Thanks again. Thought about that too and gave it a whirl. No dice:

```
        server.setGlobalFlag(MinecraftConstants.SERVER_LOGIN_HANDLER_KEY, (ServerLoginHandler) session -> {
            final GameProfile profile = session.getFlag(MinecraftConstants.PROFILE_KEY);
            session.send(new ServerJoinGamePacket(0, true, GameMode.SURVIVAL, 0, Difficulty.PEACEFUL, 10, WorldType.DEFAULT, false));
            final ByteBuf buffer = Unpooled.buffer();
            final ByteBufNetOutput adapter = new ByteBufNetOutput(buffer);
            try {
                adapter.writeString("Sponge");
            } catch (IOException e) {
                SpongeGame.logger.error(e.toString());
            }
            session.send(new ServerPluginMessagePacket("MC|Brand", buffer.array()));
            session.send(new ServerSpawnPositionPacket(new Position(0, 64, 0)));
            session.send(new ServerPlayerAbilitiesPacket(false, false, false, true, 0.05f, 0.1f));
            session.send(new ServerPlayerPositionRotationPacket(0, 64, 0, 0, 0, 0));
            for (Session activeSession : sessions) {
                activeSession
                        .send(new ServerPlayerListEntryPacket(PlayerListEntryAction.ADD_PLAYER, new PlayerListEntry[]{new PlayerListEntry(profile,
                                GameMode.CREATIVE, 10, new TextMessage(profile.getName()))}));

                if (activeSession != session) {
                    final GameProfile otherProfile = activeSession.getFlag(MinecraftConstants.PROFILE_KEY);
                    session.send(
                            new ServerPlayerListEntryPacket(PlayerListEntryAction.ADD_PLAYER, new PlayerListEntry[]{new PlayerListEntry(otherProfile,
                                    GameMode.CREATIVE, 10, new TextMessage(otherProfile.getName()))}));
                }

                activeSession.send(new ServerChatPacket(profile.getName() + " has joined the game."));
            }


            final BlockState state = new BlockState(1, 0);
            final List<Column> columns = new ArrayList<>();
            for (int cx = 0; cx < 16; cx++) {
                for (int cz = 0; cz < cx; cz++) {
                    final Chunk[] sections = new Chunk[16];
                    for (int section = 0; section < 16; section++) {
                        final Chunk chunk = new Chunk(true);

                        for (int bx = 0; bx < 16; bx++) {
                            for (int bz = 0; bz < bx; bz++) {
                                for (int by = 0; by < bz; by++) {
                                    if (new Random().nextBoolean()) {
                                        chunk.getBlocks().set(bx, by, bz, state);
                                    }
                                }
                            }
                        }

                        sections[section] = chunk;
                    }

                    final byte[] biomeData = new byte[256];
                    Arrays.fill(biomeData, (byte) 0);
                    columns.add(new Column(cx, cz, sections, biomeData));
                }
            }

            for (Column column : columns) {
                session.send(new ServerChunkDataPacket(column));
            }
```

**Comment by Zidane** [comment]
I've tried to lower the amount of columns and just send 1 like above. Still nothing. Very odd...this should be working...

**Comment by Steveice10** [comment]
Is it intentional that in your for loops, the Z coordinate variables are limited to the current X values? (i.e. "cz < cx")

**Comment by Zidane** [comment]
@Steveice10 

Not intentional. Just been throwing values at the wall, see what sticks.

**Comment by Zidane** [comment]
Got this resolved, am able to send chunks. Thanks again @Steveice10 :).
