### ISSUE TITLE
Crash when lightning strikes

### ISSUE THREAD

**Issue by goosewoman** [GeyserMC/MCProtocolLib#18]
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsExceptio
n: 1
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageD
ecoder.java:258)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:140)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCo
dec.java:108)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(Chann
elHandlerInvokerUtil.java:74)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(Defau
ltChannelHandlerInvoker.java:138)
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(Default
ChannelHandlerContext.java:317)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:154)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCo
dec.java:108)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(Chann
elHandlerInvokerUtil.java:74)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(Defau
ltChannelHandlerInvoker.java:138)
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(Default
ChannelHandlerContext.java:317)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:154)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCo
dec.java:108)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(Chann
elHandlerInvokerUtil.java:74)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(Defau
ltChannelHandlerInvoker.java:138)
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(Default
ChannelHandlerContext.java:317)
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHa
ndler.java:148)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(Chann
elHandlerInvokerUtil.java:74)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(Defau
ltChannelHandlerInvoker.java:138)
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(Default
ChannelHandlerContext.java:317)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChanne
lPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstra
ctNioByteChannel.java:123)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav
a:485)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve
ntLoop.java:452)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThread
EventExecutor.java:794)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at ch.spacebase.mc.protocol.packet.ingame.server.entity.spawn.ServerSpaw
nGlobalEntityPacket.read(ServerSpawnGlobalEntityPacket.java:51)
        at ch.spacebase.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:
36)
        at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec
.java:42)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageD
ecoder.java:227)
        ... 26 more

**Comment by minecraftkeba** [comment]
I still get the same error
