### ISSUE TITLE
Unable to login with access token

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#201]
Whenever I try logging into an account with just the token and username I'm unable too.
**Code**: 
this.client = new Client(host, port, new MinecraftProtocol(email, token, true), new TcpSessionFactory());

**Stacktrace**:
org.spacehq.mc.auth.exception.request.InvalidCredentialsException: Invalid token.
	at org.spacehq.mc.auth.util.HTTP.makeRequest(HTTP.java:78)
	at org.spacehq.mc.auth.service.AuthenticationService.loginWithToken(AuthenticationService.java:315)
	at org.spacehq.mc.auth.service.AuthenticationService.login(AuthenticationService.java:211)
	at org.spacehq.mc.protocol.MinecraftProtocol.<init>(MinecraftProtocol.java:93)
	at org.spacehq.mc.protocol.MinecraftProtocol.<init>(MinecraftProtocol.java:79)
	at com.github.coughdropdev.XXX.XX.<init>(Bot.java:25)
	at com.github.coughdropdev.XXX.X$3.run(X.java:359)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)

**Comment by Steveice10** [comment]
Make sure the token hasn't expired or been invalidated by a logout.
