### ISSUE TITLE
Protocol Error

### ISSUE THREAD

**Issue by filipejsfreitas** [GeyserMC/MCProtocolLib#22]
Using your maven repository and using build "1.7.4-SNAPSHOT" of the Library, I can't get my clients to connect to my server. I think it's a protocol error because of the strack trace:

[03:33:04 WARN](...): io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: 23
[03:33:04 WARN](...): at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:258)
[03:33:04 WARN](...): at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:140)
[03:33:04 WARN](...): at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
[03:33:04 WARN](...): at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
[03:33:04 WARN](...): at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
[03:33:04 WARN](...): at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
[03:33:04 WARN](...): at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:154)
[03:33:04 WARN](...): at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
[03:33:04 WARN](...): at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
[03:33:04 WARN](...): at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
[03:33:04 WARN](...): at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
[03:33:04 WARN](...): at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:154)
[03:33:04 WARN](...): at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
[03:33:04 WARN](...): at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
[03:33:04 WARN](...): at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
[03:33:04 WARN](...): at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
[03:33:04 WARN](...): at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:148)
[03:33:04 WARN](...): at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
[03:33:04 WARN](...): at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
[03:33:04 WARN](...): at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
[03:33:04 WARN](...): at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
[03:33:04 WARN](...): at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
[03:33:04 WARN](...): at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
[03:33:04 WARN](...): at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
[03:33:04 INFO]: (Client Name Here) lost connection: Disconnected
[03:33:04 WARN](...): at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
[03:33:04 WARN](...): at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
[03:33:04 WARN](...): at java.lang.Thread.run(Thread.java:722)
[03:33:04 WARN](...): Caused by: java.lang.ArrayIndexOutOfBoundsException: 23
[03:33:04 WARN](...): at ch.spacebase.mc.protocol.packet.ingame.server.entity.ServerEntityEffectPacket.read(ServerEntityEffectPacket.java:46)
[03:33:04 WARN](...): at ch.spacebase.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:36)
[03:33:04 WARN](...): at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
[03:33:04 WARN](...): at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:227)

26 more

The netty exception is generated by the reading of the ServerEntityEffectPacket.

Can you please take a look? Thanks!

**Comment by filipejsfreitas** [comment]
As I said, I use maven to handle dependencies. So, which version should I use to get this issue fixed? Thanks!
