### ISSUE TITLE
Mapping Issue

### ISSUE THREAD

**Issue by ChazzaIO** [GeyserMC/MCProtocolLib#223]
Following error when joining servers

`Caused by: java.lang.IllegalArgumentException: Value  has no mapping for key class com.github.steveice10.mc.protocol.data.game.scoreboard.NameTagVisibility.
	at com.github.steveice10.mc.protocol.data.MagicValues.key(MagicValues.java:1027)
	at com.github.steveice10.mc.protocol.packet.ingame.server.scoreboard.ServerTeamPacket.read(ServerTeamPacket.java:130)
	at com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:41)
	at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 38 more`

**Comment by phase** [comment]
This just happened for me: 
```
java.lang.IllegalArgumentException: Value 465 has no mapping for key class com.github.steveice10.mc.protocol.data.game.world.sound.BuiltinSound.
```

**Comment by Steveice10** [comment]
@ChazzaIO Fixed.
@phase This has already been fixed.
