### ISSUE TITLE
Protocol Error

### ISSUE THREAD

**Issue by filipejsfreitas** [GeyserMC/MCProtocolLib#23]
Once again, I think you might have a protocol error in the library.

[15:28:10 WARN]: io.netty.handler.codec.DecoderException: java.lang.NegativeArraySizeException
[15:28:10 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:258)
[15:28:10 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:140)
[15:28:10 WARN]: at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
[15:28:10 WARN]: at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
[15:28:10 WARN]: at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
[15:28:10 WARN]: at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
[15:28:10 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:154)
[15:28:10 WARN]: at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
[15:28:10 WARN]: at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
[15:28:10 WARN]: at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
[15:28:10 WARN]: at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
[15:28:10 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:154)
[15:28:10 WARN]: at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
[15:28:10 WARN]: at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
[15:28:10 WARN]: at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
[15:28:10 WARN]: at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
[15:28:10 WARN]: at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:148)
[15:28:10 WARN]: at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
[15:28:10 WARN]: at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
[15:28:10 WARN]: at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
[15:28:10 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
[15:28:10 WARN]: at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
[15:28:10 WARN]: at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
[15:28:10 WARN]: at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
[15:28:10 WARN]: at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
[15:28:10 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
[15:28:10 WARN]: at java.lang.Thread.run(Thread.java:722)
[15:28:10 WARN]: Caused by: java.lang.NegativeArraySizeException
[15:28:10 WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.nio.channels.ClosedChannelException
[15:28:10 WARN]: at ch.spacebase.mc.protocol.packet.ingame.server.world.ServerMapDataPacket.read(ServerMapDataPacket.java:49)
[15:28:10 WARN]: at ch.spacebase.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:36)
[15:28:10 WARN]: at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
[15:28:10 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:227)
[15:28:10 WARN]: ... 26 more
[15:28:10 WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.nio.channels.ClosedChannelException

Can you please take a look again? Sorry and thanks!

**Comment by earthonion** [comment]
What were you trying to do? This was probably caused because there are no colors in the rest of the byte array.

**Comment by filipejsfreitas** [comment]
I was trying to connect a bot to a server.
