### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by DataPools** [GeyserMC/MCProtocolLib#231]
On my personal computer, the program is able to successfully login and create a session. However, on my VPS it keeps saying Invalid Credentials.

Is there any way to fix this?

**Comment by Steveice10** [comment]
Are you providing different credentials on the VPS, and are you sure they're valid?

**Comment by DataPools** [comment]
Credentials are built into the program. The compiled jar runs fine on my pc but starts giving invalid credential on my vps. 

I used curl and POSTed a request to authserver.mojang.com on both my computer and VPS. On my PC, a session token is returned, on my VPS with the exact same command an Invalid Credentials: "Invalid username or password" response is returned.

Is there a location lock or something?

**Comment by Steveice10** [comment]
Are you certain that your VPS can properly access the Mojang authentication servers, then?

**Comment by DataPools** [comment]
I'm pretty sure it can, it was able to connect and POST a request on VPS. It's just the authserver gives a different output.

https://gaming.stackexchange.com/questions/259381/does-mojang-blacklist-or-throttle-login-attempts-from-specific-ip-addresses

Perhaps my VPS is permanently blacklisted?

**Comment by DataPools** [comment]
Is there a way to use a proxy for login requests with MCProtocolLib?

**Comment by Steveice10** [comment]
Yes. See https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/MinecraftProtocol.java#L174

**Comment by DataPools** [comment]
Using a proxy with MinecraftProtocol, even running on my personal computer still seem to give the same error. Is there a location lock of some sort on Minecraft accounts?

**Comment by stenocyb** [comment]
A lot of proxies are blocked by mojang. Transparent proxies won't work. Which proxy do you run on your computer? Make sure the requests don't contain the X-Forwarded-For header. [https://en.wikipedia.org/wiki/X-Forwarded-For](wikipedia)

**Comment by DataPools** [comment]
I was using a SOCKS5 proxy from a proxy list. It was a High anonymity proxy when I tested it. I found a proxy that authenticates fine, however I am getting an invalid token exception every time I use it.

**Comment by stenocyb** [comment]
Yes, I think your VPS' ip has most likely been blocked. As for the illegal access token, I think this could be a problem with the proxy. Public proxies are extremely unreliable and have all sorts of problems. You could try using tor as an auth proxy, however I haven't tried this myself. Maybe try some more proxies?

**Comment by DataPools** [comment]
I've tried a lot of proxies so far. It seems to authenticate correctly, just when logging in it gets an invalid token. I've tested many proxies and most succeed in authenticating but fail to login and get an invalid token error.

**Comment by stenocyb** [comment]
Have you tried if this proxy actually forwards the traffic correctly? Check your code where you authenticate the client. When creating the MinecraftProtocol, set the boolean parameter 'token' to false, not true. For example: `MinecraftProtocol protocol = new MinecraftProtocol("myacc@example.com", "password", false, proxy);`. This is most likely why it doesn't work.

**Comment by DataPools** [comment]
Token is already set to false.

I have an test that uses ipify.org to print out the ip of the client in order to verify the proxy is working.

**Comment by 0-x-2-2** [comment]
mojang blocks most proxys and vpns

**Comment by DataPools** [comment]
I'm getting an invalid token. It authenticates fine through program. 

Even using the example class with my proxy gives an invalid token exception even though it authenticates with Mojang fine. It just gives an invalid token exception when logging in to a server.

**Comment by DataPools** [comment]
Update: I've tried running it through Tor. I am running the example java code. I don't get any errors with no proxy. When I start using the Tor proxy I get this error:

This is the same error I get with working proxies.

```
com.github.steveice10.mc.auth.exception.request.InvalidCredentialsException: Invalid token
	at com.github.steveice10.mc.auth.util.HTTP.makeRequest(HTTP.java:79)
	at com.github.steveice10.mc.auth.service.SessionService.joinServer(SessionService.java:104)
	at com.github.steveice10.mc.protocol.ClientListener.packetReceived(ClientListener.java:55)
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:142)
	at com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:48)
	at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.oio.AbstractOioByteChannel.doRead(AbstractOioByteChannel.java:162)
	at io.netty.channel.oio.AbstractOioChannel$1.run(AbstractOioChannel.java:37)
	at io.netty.channel.ThreadPerChannelEventLoop.run(ThreadPerChannelEventLoop.java:67)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by 0-x-2-2** [comment]
tor is also blocked

**Comment by DataPools** [comment]
Is it really possible to block every Tor exit node? Plus, as I said before it gets an invalid token.

I used Tor and POSTed a request to Mojang's auth server and got a successful response back. Obviously, Tor is not the problem. It's the invalid sessions that are the problem.

**Comment by Steveice10** [comment]
Try also using this line: https://github.com/Steveice10/MCProtocolLib/blob/62bb2240ba46118ad883627878b30b770d712525/example/com/github/steveice10/mc/protocol/test/MinecraftProtocolTest.java#L156

**Comment by DataPools** [comment]
Where do I get the Auth Proxy token?

**Comment by DataPools** [comment]
It works! Thanks for this awesome library!

**Comment by 0-x-2-2** [comment]
lol
