### ISSUE TITLE
Respawn problem unregistered outgoing packet

### ISSUE THREAD

**Issue by NovaBlastHD** [GeyserMC/MCProtocolLib#235]
The reason I registered a packet when I was trying to respawn a player was because I got this unregistered outgoing packet error. I grabbed all the data that I needed to respawn a player and I tried to respawn them, but I get this:
Unregistered outgoing packet class: org.spacehq.mc.protocol.packet.ingame.server.ServerRespawnPacket

Any way to fix this? I have respawn set up properly. I read the protocol.

**Comment by NovaBlastHD** [comment]
More specifically:
`io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unregistered outgoing packet class: org.spacehq.mc.protocol.packet.ingame.server.ServerRespawnPacket
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at io.netty.handler.codec.ByteToMessageCodec.write(ByteToMessageCodec.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:748)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:740)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1101)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1148)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1090)
	at io.netty.channel.ThreadPerChannelEventLoop.run(ThreadPerChannelEventLoop.java:67)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Unregistered outgoing packet class: org.spacehq.mc.protocol.packet.ingame.server.ServerRespawnPacket
	at org.spacehq.packetlib.packet.PacketProtocol.getOutgoingId(PacketProtocol.java:141)
	at org.spacehq.packetlib.tcp.TcpPacketCodec.encode(TcpPacketCodec.java:26)
	at org.spacehq.packetlib.tcp.TcpPacketCodec.encode(TcpPacketCodec.java:16)
	at io.netty.handler.codec.ByteToMessageCodec$Encoder.encode(ByteToMessageCodec.java:172)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 10 more`

**Comment by stenocyb** [comment]
Why do you want to register packets? There is no need to do this. Read the example code (https://github.com/Steveice10/MCProtocolLib/blob/master/example/com/github/steveice10/mc/protocol/test/MinecraftProtocolTest.java)

**Comment by Steveice10** [comment]
You're likely sending the packet before the protocol enters in-game mode, which can't be done.

**Comment by NovaBlastHD** [comment]
I have the client in the game. And the protocol is in the game also. They can talk in chat etc. But once I try to respawn them I get an unregistered packet (client side). But I am not sending packets since you told me not to. I get this error. Even if I check if the player is online and then put executing code in that I get this error.

**Comment by Steveice10** [comment]
Ahh, the issue here is that you're trying to send a server packet from the client. You can't do that either.

**Comment by NovaBlastHD** [comment]
Yes this is my problem, thanks for pointing this out.

**Comment by jonesdj1** [comment]
@Steveice10 is there a way currently to check if there in in-game mode?

**Comment by 109C** [comment]
@jonesdj1 `((MinecraftProtocol)session.getPacketProtocol()).getSubProtocol() == SubProtocol.GAME`

**Comment by jonesdj1** [comment]
Thanks!
