### ISSUE TITLE
Why im getting this error io.netty.handler.codec.EncoderException

### ISSUE THREAD

**Issue by Dojdik** [GeyserMC/MCProtocolLib#243]
Disconnected: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unregistered outgoing packet class: com.github.steveice10.mc.protocol.packet.ingame.client.ClientChatPacket
[08:53:37 WARN]: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unregistered outgoing packet class: com.github.steveice10.mc.protocol.packet.ingame.client.ClientChatPacket
[08:53:37 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[08:53:37 WARN]:        at io.netty.handler.codec.ByteToMessageCodec.write(ByteToMessageCodec.java:108)
[08:53:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[08:53:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[08:53:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
[08:53:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1089)
[08:53:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1136)
[08:53:37 WARN]:        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1078)
[08:53:37 WARN]:        at io.netty.channel.ThreadPerChannelEventLoop.run(ThreadPerChannelEventLoop.java:67)
[08:53:37 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[08:53:37 WARN]:        at java.lang.Thread.run(Unknown Source)
[08:53:37 WARN]: Caused by: java.lang.IllegalArgumentException: Unregistered outgoing packet class: com.github.steveice10.mc.protocol.packet.ingame.client.ClientChatPacket
[08:53:37 WARN]:        at com.github.steveice10.packetlib.packet.PacketProtocol.getOutgoingId(PacketProtocol.java:141)
[08:53:37 WARN]:        at com.github.steveice10.packetlib.tcp.TcpPacketCodec.encode(TcpPacketCodec.java:26)
[08:53:37 WARN]:        at com.github.steveice10.packetlib.tcp.TcpPacketCodec.encode(TcpPacketCodec.java:16)
[08:53:37 WARN]:        at io.netty.handler.codec.ByteToMessageCodec$Encoder.encode(ByteToMessageCodec.java:172)
[08:53:37 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[08:53:37 WARN]:        ... 10 more

**Comment by Steveice10** [comment]
Are you sending it from a client, and have you made sure that the protocol is in the in-game state?

**Comment by 0-x-2-2** [comment]
You're not in the in-game state

**Comment by Dojdik** [comment]
How I can check i'm ingame state or not? I using this code
        MinecraftProtocol protocol = null;
        protocol = new MinecraftProtocol(USERNAME);
        client = new Client(HOST, PORT, protocol, new TcpSessionFactory(PROXY));
        client.getSession().setFlag(MinecraftConstants.AUTH_PROXY_KEY, AUTH_PROXY);
        client.getSession().connect(true);

**Comment by Mareckoo01** [comment]
@Dojdik don't send chat packets before you receive ServerJoinGamePacket and also why you don't just use .connect(); ?

**Comment by Steveice10** [comment]
As @Mareckoo01 mentioned, you should probably listen and wait for a ServerJoinGamePacket. For future reference though, you can call getSubProtocol() on a MinecraftProtocol instance to check its state.
