### ISSUE TITLE
MinecraftProtocol can't connect with proxy

### ISSUE THREAD

**Issue by bddvlpr** [GeyserMC/MCProtocolLib#250]
Hey, i'm using  
`this.protocol = new MinecraftProtocol(username, password,false , proxy);`  
as  code with a proxy set, but i keep getting this weird exception  
`[Veneficus] [ERROR] Failed loggin in 'HIDDEN@HIDDEN:HIDDEN! Invalid credentials.
com.github.steveice10.mc.auth.exception.request.InvalidCredentialsException: Invalid credentials. Invalid username or password.
    at com.github.steveice10.mc.auth.util.HTTP.makeRequest(HTTP.java:79)
    at com.github.steveice10.mc.auth.service.AuthenticationService.loginWithPassword(AuthenticationService.java:280)
    at com.github.steveice10.mc.auth.service.AuthenticationService.login(AuthenticationService.java:217)
    at com.github.steveice10.mc.protocol.MinecraftProtocol.<init>(MinecraftProtocol.java:191)
    at org.veneficus.bot.Core.BotClient.getProtocol(BotClient.java:52)
    at org.veneficus.bot.Core.BotClient.<init>(BotClient.java:42)
    at org.veneficus.bot.Core.Threads.StartBotsThread.run(StartBotsThread.java:31)
    at java.lang.Thread.run(Thread.java:748)`

Logging in with that account on minecraft.net works.

**Comment by Mareckoo01** [comment]
Check if username/email and password are correct, try logging in with email if you are using username or the other way around...

**Comment by bddvlpr** [comment]
@Mareckoo01 Logging in in the launcher works and logging in without a proxy works too.

**Comment by Mareckoo01** [comment]
Then that proxy is banned by mojang. [They even ban accounts nowdays...](https://www.reddit.com/r/Minecraft/comments/5vwve1/mojang_now_ban_accounts_for_vpn_usage/)

**Comment by kingdevnl** [comment]
But how do you tell if a Proxy its banned?

**Comment by Mareckoo01** [comment]
Well.. if it is public and used by enough people, the chance of it being banned increases? or by trying to login with it and it doesn't work?

**Comment by bddvlpr** [comment]
Well, it is public, but just got uploaded this very day, so i don't really see what could've happened.

**Comment by Mareckoo01** [comment]
That doesn't mean that it wasn't used before..

**Comment by bddvlpr** [comment]
Probably banned proxy

**Comment by 0-x-2-2** [comment]
alot of proxys are banned from mojang
