### ISSUE TITLE
AbstractMethodError

### ISSUE THREAD

**Issue by NovaBlastHD** [GeyserMC/MCProtocolLib#256]
I'm using mcprotocollib 1.12.1, and mcprotocollib 1.8.
My goal is to be able to connect to servers and select what version the server is then you connect.
All my code is wrote, everything works fine, but I noticed that the lib that was added to the build path last doesn't work and spits out this error:
`java.lang.AbstractMethodError: io.netty.channel.SimpleChannelInboundHandler.channelRead0(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.oio.AbstractOioByteChannel.doRead(AbstractOioByteChannel.java:162)
	at io.netty.channel.oio.AbstractOioChannel$1.run(AbstractOioChannel.java:37)
	at io.netty.channel.ThreadPerChannelEventLoop.run(ThreadPerChannelEventLoop.java:67)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)`
I moved around the order of the lib, and it seemed that the lib that was broken worked, and the one that worked was broken and spat out the same error.

Anyway around this?

**Comment by Steveice10** [comment]
I don't quite understand; why/how are you using two versions of the library at once? If you are trying to include both jars in one project, they might be conflicting.

**Comment by NovaBlastHD** [comment]
I'm using a interface with two classes. The two classes are protocol for 1.8, and protocol for 1.12.1. When I switch the order of the libs, the lib that loaded last doesn't work. I'm unsure why this happens, and believe the two libs are conflicting for some reason. Is there code I could remove from 1.12.1 that would possibly stop this from happening?

**Comment by NovaBlastHD** [comment]
My goal is to use an interface to effectively be able to manage multiple versions of the library. My code worked when I removed either library. But that's my dilemma, I need both libraries. I don't want to have to make multiple programs for different versions of the library.

**Comment by Steveice10** [comment]
The best way to use two versions of the library at once would probably be to change each to have a unique package name based on their version at compile time. MCProtocolLib simply isn't designed for multi-version support out-of-the-box.

**Comment by Mareckoo01** [comment]
If you are looking for different MCPL versions, [my repo might save you some time](https://github.com/Mareckoo01/MCProtocolLib).
###### Check pom for dependencies in every branch.

**Comment by NovaBlastHD** [comment]
I'm not exactly looking for that currently, Mareckoo01, but that sure will be handy for me in the future. In response to Steveice, I've been using org.spacehq for 1.8, and the github packaging for 1.12.1. What else is there to change? The dependency names have to be changed?

**Comment by Steveice10** [comment]
Yes. The multiple instances of dependencies like netty are probably conflicting with each other.

**Comment by NovaBlastHD** [comment]
Ah okay thanks.

**Comment by liian2018** [comment]
I met the same problem, but my error is the spring-boot-starter-data-redis 2.0.3 in conflict with netty-all 5.0.0.Alpha2
