### ISSUE TITLE
Unregistered outgoing packet class: org.spacehq.mc.protocol.packet.ingame.client.player.ClientPlayerPositionPacket 

### ISSUE THREAD

**Issue by Lennyss** [GeyserMC/MCProtocolLib#263]
So i try to use this code:
https://gist.github.com/Lennyss/cd5e95d27b763ae3c9291be568e8628e
and when i join to my local server i have "dowloading terrain" and this error:
[code]
sR-org.spacehq.mc.protocol.packet.ingame.client.player.ClientPlayerPositionPacket@69cfb96e
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unregistered outgoing packet class: org.spacehq.mc.protocol.packet.ingame.client.player.ClientPlayerPositionPacket
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at io.netty.handler.codec.ByteToMessageCodec.write(ByteToMessageCodec.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:748)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:740)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1101)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1148)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1090)
	at io.netty.util.concurrent.SingleThreadEventExecutor.safeExecute(SingleThreadEventExecutor.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:401)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unregistered outgoing packet class: org.spacehq.mc.protocol.packet.ingame.client.player.ClientPlayerPositionPacket
	at com.github.steveice10.packetlib.packet.PacketProtocol.getOutgoingId(PacketProtocol.java:141)
	at com.github.steveice10.packetlib.tcp.TcpPacketCodec.encode(TcpPacketCodec.java:26)
	at com.github.steveice10.packetlib.tcp.TcpPacketCodec.encode(TcpPacketCodec.java:16)
sR-org.spacehq.mc.protocol.packet.ingame.client.player.ClientPlayerPositionPacket@23408905
	at io.netty.handler.codec.ByteToMessageCodec$Encoder.encode(ByteToMessageCodec.java:172)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 13 more
[/code]
i use 1.8.8 mcprotocolib version

EDIT:
i added this:
                                    MinecraftProtocol protocol = (MinecraftProtocol) client.getSession().getPacketProtocol();
                                    if (protocol.getSubProtocol() != SubProtocol.GAME) {
                                        return;
                                    }
before sending ClientPlayerPositionRotationPacket but still have same error ;/

**Comment by Steveice10** [comment]
You are receiving packets from a client and then sending them to a client. You cannot send client-to-server packets to a client, only to a server.

**Comment by Lennyss** [comment]
@Steveice10  so can you tell me what i should change in this code?

**Comment by Steveice10** [comment]
I actually seem to have slightly misinterpreted what your code is doing, but the gist of it is that you need to make sure you're only sending packets prefixed "Client" from client to server and packets prefixed "Server" from server to client. You probably also need to check the protocol mode of "client" before you send packets on line 30.

**Comment by Lennyss** [comment]
@Steveice10  ok i fix this, i don't finish login sequence, thats my problem :)
