### ISSUE TITLE
Switching session?

### ISSUE THREAD

**Issue by Lennyss** [GeyserMC/MCProtocolLib#267]
So i make server on localhost, i can login etc, but how to connect to another server f.e connect to hypixel.net
I'am trying to connect bot to server and later send packet from bot to player , but i have exception like
"
The connection was terminated by software installed on the host computer"
before i send packet to player i check if player and bot is in SubProtocol.GAME and packet is not LoginSuccess cuz i have errors with unregister outgoing...

**Comment by Steveice10** [comment]
Sounds like it might be a connection problem. There is an example in the source if you want to make sure you're doing things correctly.

**Comment by Lennyss** [comment]
I fixed this but i have a lot of other errors like:
Caused by: java.lang.IllegalArgumentException: String cannot be null!
	at org.spacehq.packetlib.tcp.io.ByteBufNetOutput.writeString(ByteBufNetOutput.java:128)
OR:
Caused by: java.lang.NullPointerException
	at org.spacehq.mc.protocol.packet.ingame.server.entity.ServerEntityStatusPacket.write(ServerEntityStatusPacket.java:42)
OR:
Caused by: java.lang.IllegalArgumentException: Invalid packet id: 0
	at org.spacehq.packetlib.packet.PacketProtocol.createIncomingPacket(PacketProtocol.java:114)
OR:
Caused by: java.lang.IllegalArgumentException: Invalid packet id: 3
	at org.spacehq.packetlib.packet.PacketProtocol.createIncomingPacket(PacketProtocol.java:114)
OR:
Caused by: java.lang.NullPointerException
	at org.spacehq.mc.protocol.packet.ingame.server.entity.ServerEntityStatusPacket.write(ServerEntityStatusPacket.java:42)
but when i log in on localhost, or other server withgout plugin or smaller servers all work ;/

@Steveice10  any ideas? i try use 1.8 cuz on 1.12 is less amount of server than 1.8

**Comment by Steveice10** [comment]
Old version are not supported.
