### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by LuckyTheCat** [GeyserMC/MCProtocolLib#27]
Proxy support would be a great addition to add. I was going to try to do so myself, but the way that the libraries are set it this seems quite difficult to do. Great work on the library. It  has been working very well.

**Comment by LuckyTheCat** [comment]
I'm sorry, I see how that could have been confusing. I mean being able to add a proxy to the client. So you could join the server with the proxy.

**Comment by LuckyTheCat** [comment]
Sorry, it's been a long day. Let me draw a diagram. Client created -> Authenticates to the Mojang servers -> Client creates server connection (The created socket that connects to the server would connect to said server with a proxy.) -> Server login, and everything else here. I hope this clears it up for you. Thanks.

**Comment by LuckyTheCat** [comment]
Thanks a bunch for adding this, but there is an issue. After adding the proxy to TcpSessionFactory it throws this Exception:

Exception in thread "Thread-0" java.net.SocketException: Connection refused: connect
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at io.netty.channel.socket.oio.OioSocketChannel.doConnect(OioSocketChannel.java:199)
    at io.netty.channel.oio.AbstractOioChannel$DefaultOioUnsafe.connect(AbstractOioChannel.java:69)
    at io.netty.channel.DefaultChannelPipeline$HeadHandler.connect(DefaultChannelPipeline.java:1040)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeConnectNow(ChannelHandlerInvokerUtil.java:108)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeConnect(DefaultChannelHandlerInvoker.java:217)
    at io.netty.channel.DefaultChannelHandlerContext.connect(DefaultChannelHandlerContext.java:375)
    at io.netty.channel.DefaultChannelHandlerContext.connect(DefaultChannelHandlerContext.java:369)
    at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:903)
    at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:194)
    at io.netty.bootstrap.Bootstrap$2.run(Bootstrap.java:213)
    at io.netty.channel.ThreadPerChannelEventLoop.run(ThreadPerChannelEventLoop.java:38)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
    at java.lang.Thread.run(Unknown Source)

If you want to see the proxy I am using:
new Proxy(Proxy.Type.SOCKS, new InetSocketAddress("94.140.232.67", 1080))

**Comment by LuckyTheCat** [comment]
I tried many socks proxies, and tested them with online tools. The ones that wouldn't work would just time out. These didn't work instantly. Are you sure that's the error? I own a few servers, and if you're that sure I'll just make add proxy support to one, and then test it that way.

**Comment by LuckyTheCat** [comment]
I tried to changing the server to offline mode. This seemed to have work. I'm not sure what is causing this, but it's probably something to do with the creation of the login with Mojangs servers. Though I don't think Mojang blocked the proxies.
Edit: To be more precise, I don't mean the logging in to create the session, I mean authenticating to said server.

**Comment by LuckyTheCat** [comment]
This is quite interesting. I guess it was a mix of bad luck, and me just being stupid. I tried more than 100 proxy servers, and was almost certain. This proxy wasn't working either at first, but I tried it multiple times and it succeeded.. I'm terribly sorry for wasting your time, but thanks for the addition, and for baring with me. :)
