### ISSUE TITLE
ReadTimeout

### ISSUE THREAD

**Issue by binarydepartment** [GeyserMC/MCProtocolLib#29]
I noticed that my bot stopped working because of an uncaught exception. Here's the message i got:

```
Apr 04, 2014 10:23:33 AM io.netty.channel.ChannelHandlerInvokerUtil invokeExceptionCaughtNow
WARNING: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.handler.timeout.ReadTimeoutException
```

**Comment by binarydepartment** [comment]
Yea sure, but wouldn't it be best if the disconnect method in the SessionAdapter would be triggered? Because that's where i hooked my reconnect logic.

**Comment by binarydepartment** [comment]
I almost thought it was fixed:

```
[WARNING] Throwable caught while firing disconnect events.
java.net.ConnectException: Connection refused: play.mcnext.net/72.20.53.8:25565
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:692)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:191)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:241)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:502)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
        at java.lang.Thread.run(Thread.java:722)
```

**Comment by binarydepartment** [comment]
What is the recommended way to reconnect btw? I do it like this currently:

``` java
    /** Authenticate a user and then join server **/
    public void auth() {

        if(client != null && client.getSession().isConnected()) {
            System.out.println("Client still connected, you need to disconnect first");
            return;
        }

        System.out.println("Authenticating user: " + this.username);
        sendIRC("Authenticating user: " + this.username);

        protocol = null;
        boolean authFailed = false;

        try {
            this.protocol = new MinecraftProtocol(this.username, this.password, false);
        } catch (AuthenticationException e) {
            System.out.println("Authentication failed");
            sendIRC("Authentication failed");
            authFailed = true;
        }

        if(authFailed) {
            pause();
            System.out.println("Retrying ...");
            sendIRC("Retrying...");
            auth();
            return;
        }

        System.out.println("Successfully authenticated");
        sendIRC("Successfully authenticated");
        join();
    }

    /** Join the server **/
    public void join() {
        System.out.println("Joining server: " + hostname);
        sendIRC("Joining Server: " + hostname);

        seconds = 0;
        client = new Client(hostname, port, protocol, new TcpSessionFactory());
        client.getSession().addListener(new BotAdapter(this));
        client.getSession().connect(true);
    }
```

**Comment by binarydepartment** [comment]
So today i got multiple java.net.ConnectException WITHOUT the "[WARNING] Throwable caught while firing disconnect events.". 

You can have a look at my entire code at https://github.com/viciousmind/MCNext-Collection-Bot
