### ISSUE TITLE
connect to other server (join)

### ISSUE THREAD

**Issue by yooniks** [GeyserMC/MCProtocolLib#313]
what i doing wrong?

https://hastebin.com/huwonehaxa.cs

i'm kicking with reason 'internal network exception'

**Comment by Lennyss** [comment]
i think you use old protocol version, you should update your protocol to newest(older version is not supported)

**Comment by yooniks** [comment]
ok thanks, but i use this:
https://hastebin.com/zosicujire.cs, and when i using command (join) nothing happens

**Comment by yooniks** [comment]
Okeyy, i changed it.
But, error:
code: https://hastebin.com/jorebusiqe.cs
error from console: 
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unregistered outgoing packet class: org.spacehq.mc.protocol.packet.ingame.server.ServerJoinGamePacket
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at io.netty.handler.codec.ByteToMessageCodec.write(ByteToMessageCodec.java:108)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeWriteNow(ChannelHandlerInvokerUtil.java:158)
	at io.netty.channel.DefaultChannelHandlerInvoker$WriteTask.run(DefaultChannelHandlerInvoker.java:440)
	at io.netty.channel.ThreadPerChannelEventLoop.run(ThreadPerChannelEventLoop.java:52)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Unregistered outgoing packet class: org.spacehq.mc.protocol.packet.ingame.server.ServerJoinGamePacket
	at org.spacehq.packetlib.packet.PacketProtocol.getOutgoingId(PacketProtocol.java:141)
	at org.spacehq.packetlib.tcp.TcpPacketCodec.encode(TcpPacketCodec.java:26)
	at org.spacehq.packetlib.tcp.TcpPacketCodec.encode(TcpPacketCodec.java:16)
	at io.netty.handler.codec.ByteToMessageCodec$Encoder.encode(ByteToMessageCodec.java:140)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 6 more

**Comment by Lennyss** [comment]
just read error lol
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unregistered outgoing packet class: org.spacehq.mc.protocol.packet.ingame.server.ServerJoinGamePacket
you try to send packet which is unregistered, so use sending packet in bad state, f.e LoginPacket in GameState....

**Comment by yooniks** [comment]
okey, i did it.
bot connect to server, but i can't connect to bot.
							connect(split[3], split[1], Integer.valueOf(split[2]));
							if (sessionBot == null)
								System.out.println("null");
							sessionBot.connect(); //?

**Comment by Lennyss** [comment]
you can't connect session to another session, just proxy packet and learn java

**Comment by yooniks** [comment]
what do you mean "proxy packet"?
i don't understand.

**Comment by yooniks** [comment]
@Lennyss

**Comment by speedAccount** [comment]
@yooniks  taki programista jak ty powinien to wiedziec ps. sprzedam joina gotowego za 20 psc XD

**Comment by yooniks** [comment]
@speedAccount spierdalaj

a "internal network exception" bylo przez to ze mialem zla wersja mcprotocollib.

**Comment by m3ku** [comment]
@speedAccount ja mam joina ale za drugim razem downloading terrain ;/
