### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by speedAccount2** [GeyserMC/MCProtocolLib#349]
reason: Internal network exception. cause: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: String cannot be null!

or

reason: Internal network exception. cause: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

when i joined to specified servers.. on others servers joining always works.

**Comment by ghost** [comment]
tak samo jak ty, Piszesz kazdemu ze "LEARN JAVA" TO samo to Ci pisze :)

**Comment by speedAccount2** [comment]
@kvba1337 a ty jestes jakis kurwa niedorobiony? ja nie pytam kurwa o jakies "jak wyslac pakiet tabcomplete" tylko mam normalny problem z mcprotocollib, wiec sie pierdolnij jebany cwelu i wykurwiaj

**Comment by Steveice10** [comment]
Can you give the full stack trace?

**Comment by kamcio96** [comment]
Wbrew pozorom `LEARN JAVA` to najlepsza odpowiedz tutaj XD

**Comment by speedAccount2** [comment]
@Steveice10 What does "stack trace" mean?
@kamcio96 wez sie juz przymknij bo tylko wkurwiasz, sam pewnie nie wiesz co jest zle, pelno serwerow mi dziala, a kilka innych juz nie, wywala nulla przy wejsciu, np, vertez.pl, sam bys tego nie fixnął.

**Comment by kamcio96** [comment]
`sam bys tego nie fixnął` sam bym nie musiał XD

I tak ciężko wrzucić w google?
http://lmgtfy.com/?q=what+is+stack+trace+in+java

Pacz, nawet po polsku działa XD
http://lmgtfy.com/?q=co+oznacza+stack+trace+java

**Comment by speedAccount2** [comment]
@Steveice10 Sended packets before kick with reason nullpointerexception(internalnetworkexception),
and sometimes:
Internal Exception: net.minecraft.util.io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 1
Internal Exception: net.minecraft.util.io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 1

target server: nssv.pl

and i can't give here code.

                            @Override
                            public void disconnected(DisconnectedEvent disconnectedEvent) {
                                System.out.println("reason: " + disconnectedEvent.getReason() + " cause: " + disconnectedEvent.getCause());
                            }
error with printstacktrace:
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at io.netty.handler.codec.ByteToMessageCodec.write(ByteToMessageCodec.java:108)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeWriteNow(ChannelHandlerInvokerUtil.java:158)
	at io.netty.channel.DefaultChannelHandlerInvoker$WriteTask.run(DefaultChannelHandlerInvoker.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:328)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877)
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706)
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661)
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)
Caused by: java.lang.NullPointerException
	at org.spacehq.mc.protocol.packet.ingame.server.entity.ServerEntityStatusPacket.write(ServerEntityStatusPacket.java:42)
	at org.spacehq.packetlib.tcp.TcpPacketCodec.encode(TcpPacketCodec.java:27)
	at org.spacehq.packetlib.tcp.TcpPacketCodec.encode(TcpPacketCodec.java:16)
	at io.netty.handler.codec.ByteToMessageCodec$Encoder.encode(ByteToMessageCodec.java:140)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 12 more

**Comment by speedAccount2** [comment]
Ok, i fixed that, because when i joined, and server send me serverrespawnpacket, position itd, i have been kicked with cause: java.net.SocketException: Connection reset

**Comment by speedAccount2** [comment]
Ok, i fixed that. Topic to close.
