### ISSUE TITLE
Error on Scoreboard packet decoding.

### ISSUE THREAD

**Issue by TrevorCow** [GeyserMC/MCProtocolLib#376]
This happens when trying to decode custom scoreboard packets.

Stacktrace:
```
Disconnected: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value 21 has no mapping for key class com.github.steveice10.mc.protocol.data.game.scoreboard.TeamColor.
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value 21 has no mapping for key class com.github.steveice10.mc.protocol.data.game.scoreboard.TeamColor.
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.oio.AbstractOioByteChannel.doRead(AbstractOioByteChannel.java:162)
	at io.netty.channel.oio.AbstractOioChannel$1.run(AbstractOioChannel.java:37)
	at io.netty.channel.ThreadPerChannelEventLoop.run(ThreadPerChannelEventLoop.java:67)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Value 21 has no mapping for key class com.github.steveice10.mc.protocol.data.game.scoreboard.TeamColor.
	at com.github.steveice10.mc.protocol.data.MagicValues.key(MagicValues.java:1080)
	at com.github.steveice10.mc.protocol.packet.ingame.server.scoreboard.ServerTeamPacket.read(ServerTeamPacket.java:130)
	at com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:41)
	at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 38 more
```

**Comment by Steveice10** [comment]
What do you mean by "custom scoreboard packet"? From the exception, it looks like you're using an invalid color value.

**Comment by TrevorCow** [comment]
That's what I thought, but I couldn't figure out how this was possible. What could cause the server to send an invalid color?

A custom scoreboard packet that isn't from Minecraft's scoreboard system, many servers just use the scoreboard for server/game info.
@Steveice10

**Comment by TrevorCow** [comment]
That's what I thought, but I couldn't figure out how this was possible. What could cause the server to send an invaild color?

**Comment by TrevorCow** [comment]
Any ideas? I was thinking maybe it was just using a different color than a team color, but it looks like you have all of them. Could it be a formatting thing? Like bold or underline text being sent in scoreboard names? @Steveice10

**Comment by Steveice10** [comment]
Are you using some existing library or plugin to generate the custom scoreboard packets? If not, are you certain you're forming them correctly?

**Comment by TrevorCow** [comment]
Oh sorry for not clarifying, I'm writing a client and the packets are coming from a real Minecraft server. The packets are valid for a normal Minecraft client, but not for MCProtocolLIB. I believe the packets not only contain color info but also contain formatting (hence the invalid "color")

**Comment by TrevorCow** [comment]
Nevermind I was looking at the protocol and it looks like it has to be a color just defining what team everyone is on... so I have no idea why the server would send 21. Although, Minecraft's Reset code is 21?

**Comment by Steveice10** [comment]
Yeah, the wiki says it should only be a value from -1 to 15. I'll have to check again later how the vanilla client handles it, when I get the chance.

**Comment by TrevorCow** [comment]
Can confirm that adding the formatting codes to the TeamColors enum it fixes the crash.
@Steveice10

**Comment by Steveice10** [comment]
That's probably the right solution, but I'll want to verify it first before making any changes.

**Comment by Steveice10** [comment]
@TrevorCow Looking at the decompiled source again, it seems that Minecraft assigns -1 as the color index for all non-color formatting codes, and should never write 21 as the color index. Reading 21 as the color index should also result in the client storing null as the team's formatting type.

Just to be save, you are using the latest version of MCProtocolLib and aren't trying to use one version of the library with a different version of Minecraft, are you?

**Comment by TrevorCow** [comment]
I am using the latest MCProtocolLib, however, the server I'm connecting too supports 1.8-1.12.2. Maybe it's the protocol hack on the spigot server? So I don't know maybe just ignoring the color values would also work? (Or setting them to -1 like Minecraft does)

**Comment by TrevorCow** [comment]
@Steveice10
