### ISSUE TITLE
Bug Cipher data failed.

### ISSUE THREAD

**Issue by binarycounter** [GeyserMC/MCProtocolLib#4]
Trying to run the Chatbot example wrapped in an Android application.
The library has been compiled using Maven on Debian 6 x86.
The Server is a vanilla 1.6.2 minecraft server running on debian. 
Bukkit servers react with the same output.

Client Log:
18.36.56 Logging In.....

Server Log:

javax.crypto.BadPaddingException: Blocktype mismatch: 0
      at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:328)
      at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:272)
      at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:356)
      at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:382)
      at javax.crypto.Cipher.doFinal(Cipher.java:1922)
      at lf.a(SourceFile:119)
      at lf.b(SourceFile:114)
      at lf.a(SourceFile:106)
      at fx.a(SourceFile:52)
      at cn.i(SourceFile:254)
      at cn.c(SourceFile:17)
      at co.run(SourceFile:94)
Cipher data failed!
java.lang.IllegalArgumentException: Missing argument
      at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:93)
      at lf.a(SourceFile:106)
      at fx.a(SourceFile:52)
      at cn.i(SourceFile:254)
      at cn.c(SourceFile:17)
      at co.run(SourceFile:94)
13-08-05 18:36:59 [INFO] Heisenberg [/91.106.224.195:56823] lost connection

**Comment by binarycounter** [comment]
Correction: The cause seems to be related to android's wierd implementation of RSA Cipher. I already found a possible solution. This can probably be closed. Sorry for any inconvenience i caused.

**Comment by binarycounter** [comment]
I found the fix! Android is handling ciphing differently. I just had to modify 2 lines of code. I will post a bugfix that will support both the standard Java VM but also the Android Dalvik VM. Cheers.
