### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by ShayBox** [GeyserMC/MCProtocolLib#426]
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/util/concurrent/GenericFutureListener
	at com.github.steveice10.packetlib.tcp.TcpSessionFactory.createServerListener(TcpSessionFactory.java:31)
	at com.github.steveice10.packetlib.Server.bind(Server.java:55)
	at com.github.steveice10.packetlib.Server.bind(Server.java:45)
	at com.shaybox.privateservers.Main.main(Main.java:85)
Caused by: java.lang.ClassNotFoundException: io.netty.util.concurrent.GenericFutureListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more

Process finished with exit code 1
```
```java
public static void main(String[] args) {
		Server server = new Server("127.0.0.1", 25565, MinecraftProtocol.class, new TcpSessionFactory(Proxy.NO_PROXY));
		server.setGlobalFlag(MinecraftConstants.AUTH_PROXY_KEY, Proxy.NO_PROXY);
		server.setGlobalFlag(MinecraftConstants.VERIFY_USERS_KEY, false);
		server.setGlobalFlag(MinecraftConstants.SERVER_INFO_BUILDER_KEY, new ServerInfoBuilder() {
			public ServerStatusInfo buildInfo(Session session) {
				return new ServerStatusInfo(new VersionInfo(MinecraftConstants.GAME_VERSION, MinecraftConstants.PROTOCOL_VERSION), new PlayerInfo(100, 0, new GameProfile[0]), new TextMessage("Hello world!"), null);
			}
		});

		server.setGlobalFlag(MinecraftConstants.SERVER_LOGIN_HANDLER_KEY, new ServerLoginHandler() {
			public void loggedIn(Session session) {
				session.send(new ServerJoinGamePacket(0, false, GameMode.SURVIVAL, 0, Difficulty.PEACEFUL, 10, WorldType.DEFAULT, false));
			}
		});

		server.setGlobalFlag(MinecraftConstants.SERVER_COMPRESSION_THRESHOLD, 100);
		server.addListener(new ServerAdapter() {
			@Override
			public void serverClosed(ServerClosedEvent event) {
				System.out.println("Server closed.");
			}

			@Override
			public void sessionAdded(SessionAddedEvent event) {
				event.getSession().addListener(new SessionAdapter() {
					@Override
					public void packetReceived(PacketReceivedEvent event) {
						if(event.getPacket() instanceof ClientChatPacket) {
							ClientChatPacket packet = event.getPacket();
							GameProfile profile = event.getSession().getFlag(MinecraftConstants.PROFILE_KEY);
							System.out.println(profile.getName() + ": " + packet.getMessage());
							Message msg = new TextMessage("Hello, ").setStyle(new MessageStyle().setColor(ChatColor.GREEN));
							Message name = new TextMessage(profile.getName()).setStyle(new MessageStyle().setColor(ChatColor.AQUA).addFormat(ChatFormat.UNDERLINED));
							Message end = new TextMessage("!");
							msg.addExtra(name);
							msg.addExtra(end);
							event.getSession().send(new ServerChatPacket(msg));
						}
					}
				});
			}

			@Override
			public void sessionRemoved(SessionRemovedEvent event) {
				MinecraftProtocol protocol = (MinecraftProtocol) event.getSession().getPacketProtocol();
				if(protocol.getSubProtocol() == SubProtocol.GAME) {
					System.out.println("Closing server.");
					event.getServer().close(false);
				}
			}
		});

		server.bind();
	}
```
Using up to date, versions of all 3 libs
Copied directly from example

**Comment by Steveice10** [comment]
You are either missing netty or have the wrong version.

**Comment by ShayBox** [comment]
Thanks, did not have netty, wasn't expecting to need it 👍

**Comment by 0-x-2-2** [comment]
lol

**Comment by ShayBox** [comment]
Is there some other dependency I need to get it to show online in the server list? I can connect but it doesn't show online at all.

**Comment by Steveice10** [comment]
As long as it isn't outputting any errors, no. Is the server port open or at least accessible to the client, and if so, what is it showing as the server status?

**Comment by ShayBox** [comment]
I'm able to connect to it, but it doesn't show as online, just shows Can't connect to the server in the list, i'm sure both my game and the server are using the same version (1.13.1)

**Comment by Steveice10** [comment]
Alright. I've opened a new issue ticket to track this [here](https://github.com/Steveice10/MCProtocolLib/issues/427), and I'll look into it shortly.
