### ISSUE TITLE
javax.crypto.BadPaddingException: Decryption error on Android

### ISSUE THREAD

**Issue by ggmoritz** [GeyserMC/MCProtocolLib#429]
This happens if i connect from Android to an 1.12.2 Server (Vanilla and Spigot). I am logged in and i get disconnected because "Connection closed.", the Server gives this Stacktrace: 

`[11:15:23 WARN]: javax.crypto.BadPaddingException: Decryption error
[11:15:23 WARN]:        at sun.security.rsa.RSAPadding.unpadV15(Unknown Source)
[11:15:23 WARN]:        at sun.security.rsa.RSAPadding.unpad(Unknown Source)
[11:15:23 WARN]:        at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363)
[11:15:23 WARN]:        at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389)
[11:15:23 WARN]:        at javax.crypto.Cipher.doFinal(Cipher.java:2164)
[11:15:23 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftEncryption.a(SourceFile:117)
[11:15:23 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftEncryption.b(SourceFile:112)
[11:15:23 WARN]:        at net.minecraft.server.v1_12_R1.PacketLoginInEncryptionBegin.b(SourceFile:50)
[11:15:23 WARN]:        at net.minecraft.server.v1_12_R1.LoginListener.a(LoginListener.java:203)
[11:15:23 WARN]:        at net.minecraft.server.v1_12_R1.PacketLoginInEncryptionBegin.a(SourceFile:39)
[11:15:23 WARN]:        at net.minecraft.server.v1_12_R1.PacketLoginInEncryptionBegin.a(SourceFile:12)
[11:15:23 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:126)
[11:15:23 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:330)
[11:15:23 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:1)
[11:15:23 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[11:15:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[11:15:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[11:15:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[11:15:23 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[11:15:23 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[11:15:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[11:15:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[11:15:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[11:15:23 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[11:15:23 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[11:15:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[11:15:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[11:15:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[11:15:23 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[11:15:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[11:15:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[11:15:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[11:15:23 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[11:15:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[11:15:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[11:15:23 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[11:15:23 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[11:15:23 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
[11:15:23 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
[11:15:23 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
[11:15:23 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
[11:15:23 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[11:15:23 WARN]:        at java.lang.Thread.run(Unknown Source)
[11:15:23 ERROR]: Cipher data failed!
[11:15:23 INFO]: com.mojang.authlib.GameProfile@56fa3948[id=<null>,name=ThisIsNotMyRealName,properties={},legacy=false] (/192.168.0.109:36941) lost connection: Internal Exception: java.lang.IllegalStateException: Invalid nonce!`

**Comment by 0-x-2-2** [comment]
Can you send the code you are using and what version of java you are running under.

**Comment by Steveice10** [comment]
Do you get any errors or other relevant log output on the client side?

**Comment by ggmoritz** [comment]
@0-x-2-2 I'm on Android 8.1 / API 27. This is my Code.  If i set online mode to false and remove the password, there is no such error. Github formats the Code wrong, https://pastebin.com/0ZrEj3Ni

**Comment by ggmoritz** [comment]
@Steveice10 No, disconnected event gives me Reason: "Connection closed.", Cause: null

**Comment by 0-x-2-2** [comment]
Yes its a issue with authenticating. I don't know what version of java android 8.1 uses I assume its still java 6 or something lol

**Comment by ggmoritz** [comment]
@0-x-2-2 idk, but minimum 7

**Comment by ggmoritz** [comment]
Accidentally closed this, sorry

**Comment by 0-x-2-2** [comment]
Try to compile MCProtocolLib with jdk 6 or 7

**Comment by ggmoritz** [comment]
@0-x-2-2 I don't have jdk 6 or 7 on my Computer and I don't see how it should change anything.

**Comment by Steveice10** [comment]
Can you check if the latest commit makes any difference?

**Comment by ggmoritz** [comment]
@Steveice10  Ok so in the latest commit i needed to update to 1.13 server. Now I get a client side Error. Disconnected Reason: java.lang.Error: Failed to generate shared key. The cause is not null so I was able to get the Stacktrace: https://pastebin.com/J9W97e25

**Comment by Steveice10** [comment]
How about now?

**Comment by ggmoritz** [comment]
@Steveice10 Now there's another Error, https://pastebin.com/W8dskxka

**Comment by ggmoritz** [comment]
@Steveice10 Somehow the logcat truncated it, https://pastebin.com/wBJYtgvF works, btw I somehow also got https://pastebin.com/P6XBm0w1 it but don't know if it's my fault

**Comment by Steveice10** [comment]
Very sorry, apparently I've been trying to test it in offline mode this whole time... It should work now.

**Comment by ggmoritz** [comment]
@Steveice10 It works fine now, thank you! When will there be a stable release (I don't care if 1.13 or 1.12)?

**Comment by Steveice10** [comment]
Generally I wait maybe a week or two to see if any bug reports to come in before I make a stable release.

If you do end up needing this fix on 1.12, by the way, you can checkout the commit of the stable 1.12 release, and you should only need to add [this change](https://github.com/Steveice10/MCProtocolLib/commit/04372d057164b1134fa28c791a5c7cbcc184a140) on top.

**Comment by ggmoritz** [comment]
@Steveice10 So I would need to compile my own version or could I do that with Jitpack/Grandle?

**Comment by Steveice10** [comment]
You would need to compile it yourself for 1.12, unfortunately. If you're referring to the latest 1.13 version, though, you should be able to provide "master-SNAPSHOT" as the version for JitPack.
