### ISSUE TITLE
Can't run Example

### ISSUE THREAD

**Issue by Emilius123** [GeyserMC/MCProtocolLib#444]
I am getting this error while running the example! 

Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/util/concurrent/GenericFutureListener
	at com.github.steveice10.packetlib.tcp.TcpSessionFactory.createServerListener(TcpSessionFactory.java:31)
	at com.github.steveice10.packetlib.Server.bind(Server.java:55)
	at com.github.steveice10.packetlib.Server.bind(Server.java:45)
	at com.github.steveice10.mc.protocol.test.MinecraftProtocolTest.main(MinecraftProtocolTest.java:108)
Caused by: java.lang.ClassNotFoundException: io.netty.util.concurrent.GenericFutureListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more

**Comment by Steveice10** [comment]
You need to make sure that netty gets included in your build. Most dependency managers like maven tend to handle sub-dependencies automatically.
