### ISSUE TITLE
Bizarre protocol issue.

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#462]
I'm attempting to create a bot using [Gjum's fork of MCProtocolLib](https://github.com/Gjum/MCProtocolLib) that freezes the version at 1.12.2 as well as adding a few things from later commits, such as the JSON Array fix for messages. But I'm having a bizarre issue with the protocol that results in a connection to the server but then an immediate disconnect due to unregistered packets.

Below is the code I am using (with credentials removed, of course):

```java
public class Program {

    @Getter private static MinecraftProtocol protocol = null;
    @Getter private static Client connection = null;
    @Getter private static Session session = null;
    @Setter private static boolean preventReconnect = false;

    public static void main(String[] args) {
        while (true) {
            logger.info("Starting connection.");
            // Authenticate
            try {
                if (SESSION_TOKEN == null) {
                    protocol = new MinecraftProtocol(MINECRAFT_USERNAME, MINECRAFT_PASSWORD, Proxy.NO_PROXY);
                } else {
                    protocol = new MinecraftProtocol(MINECRAFT_USERNAME, CLIENT_TOKEN, SESSION_TOKEN, Proxy.NO_PROXY);
                }
            }
            catch (RequestException error) {
                logger.warn("Was unable to authenticate: " + error.getMessage());
                break;
            }
            CLIENT_TOKEN = protocol.getClientToken();
            SESSION_TOKEN = protocol.getAccessToken();
            logger.info("Authenticated successfully.");
            // Connection
            connection = new Client(MINECRAFT_SERVER, MINECRAFT_PORT, protocol, new TcpSessionFactory(Proxy.NO_PROXY));
            session = connection.getSession();
            for (SessionListener listener : EVENT_LISTENERS) {
                logger.debug("Event listener added: " + listener.getClass().getSimpleName());
                session.addListener(listener);
            }
            session.connect(true);
            if (!session.isConnected()) {
                logger.warn("Was unable to connect.");
                long delay = exponential.getDelay(); // Just some class I made to return increasingly higher wait times
                logger.info("Waiting... " + Time.formatDelay(delay));
                try {
                    Thread.sleep(delay);
                }
                catch (InterruptedException ignored) {
                    logger.warn("Could not complete wait!");
                }
                continue;
            }
            logger.info("Connected to server.");
            // Wait for the bot to disconnect
            while (session.isConnected()) {
                try {
                    Thread.sleep(Time.Second);
                }
                catch (InterruptedException ignored) {
                    break;
                }
            }
            logger.info("Disconnected from server.");
            if (preventReconnect) {
                logger.info("Connection undesired, backing out.");
                break;
            }
            logger.info("Waiting... " + Time.formatDelay(Time.Minute));
            try {
                Thread.sleep(Time.Minute);
            }
            catch (InterruptedException ignored) {}
            // Reset values
            protocol = null;
            connection = null;
            session = null;
        }
    }

}
```

Authentication works, even when it loops around again and uses a session token and not the password, all's seemingly good there. But instantly after connecting to the server it disconnects, here's the output:

```
[16:19:35] [INFO] Starting connection.
[16:19:35] [INFO] Authenticated successfully.
[16:19:35] [DEBUG] Event listener added: Ticker
[16:19:35] [DEBUG] Event listener added: Messages
[16:19:35] [DEBUG] Event listener added: ChatListener
[16:19:35] [DEBUG] Event listener added: DisconnectListener
[16:19:35] [INFO] Connected to server.
[16:16:31] [INFO] Disconnection: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Invalid packet id: 1
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Invalid packet id: 1
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.oio.AbstractOioByteChannel.doRead(AbstractOioByteChannel.java:168) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.oio.AbstractOioChannel$1.run(AbstractOioChannel.java:37) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.ThreadPerChannelEventLoop.run(ThreadPerChannelEventLoop.java:67) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.25.Final.jar:4.1.25.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.IllegalArgumentException: Invalid packet id: 1
        at com.github.steveice10.packetlib.packet.PacketProtocol.createIncomingPacket(PacketProtocol.java:114) ~[packetlib-1.3.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:40) ~[packetlib-1.3.jar:?]
        at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
        ... 30 more
[16:20:37] [INFO] Disconnected from server.
[16:20:37] [INFO] Waiting... 1m0s
```

What's perhaps even more perplexing is that running an older project works just fine, both in authentication and keeping connected to the server so it's not like there's been a change in protocol that's been unaccounted for. I'm completely stumped, I'm using the default classes and have followed the example code very closely.

Any ideas?

**Comment by ghost** [comment]
Nevermind, after more experimentation I've found the issue. My `Ticker` class broadcasts a `TickEvent` every 16th of a second once it receives the first `ConnectedEvent` or any its children, but apparently this screws with something fundamental during the handshake phase of connecting to the server. And so the solution was to check only begin broadcasting after `SubProtocol.GAME` had been set.
