### ISSUE TITLE
Trying to run example script but getting error

### ISSUE THREAD

**Issue by maximgeerinck** [GeyserMC/MCProtocolLib#48]
i am getting the following error when trying to run the example script ( Just the chat/login example)

``` java
Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lio/netty/channel/DefaultChannelId;
09-17 15:11:47.314    5344-5344/myapp W/System.err﹕ Failed to establish connection.
09-17 15:11:47.314    5344-5344/myapp W/System.err﹕ io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioSocketChannel
09-17 15:11:47.314    5344-5344/myapp W/System.err﹕ at io.netty.bootstrap.Bootstrap$BootstrapChannelFactory.newChannel(Bootstrap.java:299)
09-17 15:11:47.314    5344-5344/myapp W/System.err﹕ at io.netty.bootstrap.Bootstrap.createChannel(Bootstrap.java:99)
09-17 15:11:47.314    5344-5344/myapp W/System.err﹕ at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:251)
09-17 15:11:47.314    5344-5344/myapp W/System.err﹕ at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:181)
09-17 15:11:47.314    5344-5344/myapp W/System.err﹕ at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:137)
09-17 15:11:47.314    5344-5344/myapp W/System.err﹕ at org.spacehq.packetlib.tcp.TcpSession.connect(TcpSession.java:67)
09-17 15:11:47.314    5344-5344/myapp W/System.err﹕ at org.spacehq.packetlib.tcp.TcpSession.connect(TcpSession.java:51)
09-17 15:11:47.314    5344-5344/myapp W/System.err﹕ at myapp.MainActivity$PlaceholderFragment$1.onClick(MainActivity.java:245)
09-17 15:11:47.314    5344-5344/myapp W/System.err﹕ at android.view.View.performClick(View.java:4640)
09-17 15:11:47.314    5344-5344/myapp W/System.err﹕ at android.view.View$PerformClick.run(View.java:19421)
09-17 15:11:47.314    5344-5344/myapp W/System.err﹕ at android.os.Handler.handleCallback(Handler.java:733)
09-17 15:11:47.314    5344-5344/myapp W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:95)
09-17 15:11:47.314    5344-5344/myapp W/System.err﹕ at android.os.Looper.loop(Looper.java:136)
09-17 15:11:47.314    5344-5344/myapp W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5579)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ Caused by: java.lang.reflect.InvocationTargetException
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ at java.lang.reflect.Constructor.constructNative(Native Method)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ at io.netty.bootstrap.Bootstrap$BootstrapChannelFactory.newChannel(Bootstrap.java:297)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ ... 18 more
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ Caused by: java.lang.NoClassDefFoundError: java.lang.management.ManagementFactory
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ at io.netty.channel.DefaultChannelId.defaultProcessId(DefaultChannelId.java:231)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:99)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:51)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:67)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ at io.netty.channel.nio.AbstractNioByteChannel.<init>(AbstractNioByteChannel.java:48)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:77)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:67)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:60)
09-17 15:11:47.324    5344-5344/myapp W/System.err﹕ ... 21 more
```

any solution for this? It's running on android

**Comment by liamcottle** [comment]
Same problem as above...
