### ISSUE TITLE
putting null in a non-null value

### ISSUE THREAD

**Issue by goosewoman** [GeyserMC/MCProtocolLib#483]
https://github.com/Steveice10/MCProtocolLib/blob/4dd7416966c41764ac574779e76583290f75bf31/src/main/java/com/github/steveice10/mc/protocol/data/game/advancement/Advancement.java#L15

https://github.com/Steveice10/MCProtocolLib/blob/fb57c4bc740fc13a86025249637792fdec111fd1/src/main/java/com/github/steveice10/mc/protocol/packet/ingame/server/ServerAdvancementsPacket.java#L59

Here you have a @NonNull tag but you let it have a null value in ServerAdvancementsPacket.java
This gave me this error after dying in a vanilla server: 

`Caused by: java.lang.NullPointerException: parentId is marked non-null but is null
        at com.github.steveice10.mc.protocol.data.game.advancement.Advancement.<init>(Advancement.java:12)
        at com.github.steveice10.mc.protocol.packet.ingame.server.ServerAdvancementsPacket.read(ServerAdvancementsPacket.java:98)
        at com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:41)
        at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        ... 41 more
Disconnected: io.netty.handler.codec.DecoderException: java.lang.NullPointerException: parentId is marked non-null but is null`

I'm using the snapshot version of protocollib

**Comment by Steveice10** [comment]
Fixed in https://github.com/Steveice10/MCProtocolLib/commit/0d4927368c2e219cbd5814002958cee0535c65d4
