### ISSUE TITLE
noSuchMethodError

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#549]
The recent update to mcAuthLib has removed the method .setproxy() from authentication service, this is a problem as MinecraftProtocol calls this in its constructor (https://imgur.com/a/TW2p6tU). Results in this error:
`SEVERE: com.github.steveice10.mc.auth.service.AuthenticationService.setProxy(Ljava/net/Proxy;)V
java.lang.NoSuchMethodError: com.github.steveice10.mc.auth.service.AuthenticationService.setProxy(Ljava/net/Proxy;)V
        at com.github.steveice10.mc.protocol.MinecraftProtocol.<init>(MinecraftProtocol.java:232)
        at com.github.steveice10.mc.protocol.MinecraftProtocol.<init>(MinecraftProtocol.java:221)
        at com.github.steveice10.mc.protocol.MinecraftProtocol.<init>(MinecraftProtocol.java:213)
        ...`
All libraries are up to date as far as I know.

**Comment by Steveice10** [comment]
setProxy is in the parent class of Authentication service, update your PacketLib version.
