### ISSUE TITLE
Dynamic load lib at runtime

### ISSUE THREAD

**Issue by pedxyuyuko** [GeyserMC/MCProtocolLib#557]
### Question
It this lib support load at runtime?
```java
URLClassLoader classLoader = (URLClassLoader)ClassLoader.getSystemClassLoader();
Method method = URLClassLoader.class.getDeclaredMethod("addURL", URL.class);
method.setAccessible(true);
method.invoke(classLoader, new File("D:/lib/1.12.2.jar").toURI().toURL());
```

### Problem
When I new a Client objcet using the code above, It said ``NoClassDefFoundError``
```
java.lang.NoClassDefFoundError: com/github/steveice10/mc/protocol/MinecraftProtocol
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.github.steveice10.mc.protocol.MinecraftProtocol
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 
```
### Pom Config
```
        <dependency>
            <groupId>com.github.steveice10</groupId>
            <artifactId>mcprotocollib</artifactId>
            <version>1.12.2-2</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/resources/lib/1.12.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.github.steveice10</groupId>
            <artifactId>mcauthlib</artifactId>
            <version>1.1</version>
        </dependency>
        <dependency>
            <groupId>com.github.steveice10</groupId>
            <artifactId>packetlib</artifactId>
            <version>1.4</version>
        </dependency>
        <dependency>
            <groupId>com.github.steveice10</groupId>
            <artifactId>opennbt</artifactId>
            <version>1.3</version>
        </dependency>
```

### Expect
I want to support mutiple game version using the dynamic jar loading.

**Comment by pedxyuyuko** [comment]
I think I made mistake on maven configuration. Sorry for disturbing

**Comment by pedxyuyuko** [comment]
I found it doesn't matter I have maven or not. If I create a ``Client`` object, It will said ``NoClassDefFoundError``

**Comment by Steveice10** [comment]
You probably need to load in JARs for PacketLib and MCAuthLib as well, and possibly Netty as well, assuming you aren't including those already.

Regardless, I'm closing this as it's an unsupported version of the library.
