### ISSUE TITLE
MessageStyle StackOverflow 

### ISSUE THREAD

**Issue by ghost** [GeyserMC/MCProtocolLib#58]
Just got new snapshot and chat test failed. 

```
Caused by: java.lang.StackOverflowError
    at org.spacehq.mc.protocol.data.message.MessageStyle.<init>(MessageStyle.java:13)
    at org.spacehq.mc.protocol.data.message.MessageStyle.<init>(MessageStyle.java:13)
    at org.spacehq.mc.protocol.data.message.MessageStyle.<init>(MessageStyle.java:13)
    at org.spacehq.mc.protocol.data.message.MessageStyle.<init>(MessageStyle.java:13)
```

**Comment by dobrakmato** [comment]
Here is a pull request fixing StackOverflowError. https://github.com/Steveice10/MCProtocolLib/pull/56
