### ISSUE TITLE
error with chunk cache on geyser

### ISSUE THREAD

**Issue by hafarooki** [GeyserMC/MCProtocolLib#582]
I enabled chunk cache on geyser and I'm getting this error:
```
[15:11:48 ERROR]: java.lang.ArrayIndexOutOfBoundsException: 342
[15:11:48 ERROR]:       at com.github.steveice10.mc.protocol.data.game.chunk.FlexibleStorage.get(FlexibleStorage.java:73)
[15:11:48 ERROR]:       at com.github.steveice10.mc.protocol.data.game.chunk.Chunk.isEmpty(Chunk.java:103)
[15:11:48 ERROR]:       at org.geysermc.connector.utils.ChunkUtils.translateToBedrock(ChunkUtils.java:105)
[15:11:48 ERROR]:       at org.geysermc.connector.network.translators.java.world.JavaChunkDataTranslator.lambda$translate$0(JavaChunkDataTranslator.java:74)
[15:11:48 ERROR]:       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:11:48 ERROR]:       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:11:48 ERROR]:       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[15:11:48 ERROR]:       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[15:11:48 ERROR]:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:11:48 ERROR]:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:11:48 ERROR]:       at java.lang.Thread.run(Thread.java:748)
```

**Comment by Steveice10** [comment]
Probably related to #580.
