### ISSUE TITLE
failed to create io_uring ring fd Cannot allocate memory

### ISSUE THREAD

**Issue by leopoldhub** [GeyserMC/MCProtocolLib#677]
Hello, 

I simply tried to run the example with the 1.18-1 version of the lib and got the following error:

`java.lang.RuntimeException: failed to create io_uring ring fd Cannot allocate memory`

Full stacktrace:

```
Exception in thread "main" java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:68)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:104)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:97)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:90)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:79)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:62)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:48)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:41)
	at com.github.steveice10.packetlib.tcp.TcpServer.bindImpl(TcpServer.java:51)
	at com.github.steveice10.packetlib.AbstractServer.bind(AbstractServer.java:131)
	at com.github.steveice10.packetlib.AbstractServer.bind(AbstractServer.java:126)
	at com.github.steveice10.packetlib.AbstractServer.bind(AbstractServer.java:121)
	at fr.leopoldhub.mcprotocollibtest.Main.main(Main.java:134)
Caused by: java.lang.RuntimeException: failed to create io_uring ring fd Cannot allocate memory
	at io.netty.incubator.channel.uring.Native.ioUringSetup(Native Method)
	at io.netty.incubator.channel.uring.Native.createRingBuffer(Native.java:169)
	at io.netty.incubator.channel.uring.IOUringEventLoop.<init>(IOUringEventLoop.java:73)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.newChild(IOUringEventLoopGroup.java:121)
	at io.netty.incubator.channel.uring.IOUringEventLoopGroup.newChild(IOUringEventLoopGroup.java:31)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	... 13 more
```

Im on ubuntu 20.04.3 and using jdk11-correto on intellij.

**Comment by rtm516** [comment]
Try this
https://github.com/netty/netty-incubator-transport-io_uring#i-tried-to-use-io_uring-but-got-javalangruntimeexception-failed-to-create-io_uring-ring-fd-cannot-allocate-memory

**Comment by leopoldhub** [comment]
I did it and it is my actual limit:
```
ulimit -l
65536
```
But it still not working...

**Comment by artnaseef** [comment]
This is turning into a major problem recently.  Increasing the memlock limit to 1GB and still getting this error.  Seeing if I can remove io_uring.

Given that the JAR is a 0.0.8 version, I don't want this on production software.

**Comment by Camotoy** [comment]
Geyser also removes io_uring - you can just exclude the package and PacketLib will handle the removal gracefully:
```xml
<exclusion>
          <groupId>io.netty.incubator</groupId>
          <artifactId>netty-incubator-transport-native-io_uring</artifactId>
</exclusion>
```
But a PR to update the dependency will also be accepted.

**Comment by artnaseef** [comment]
That works really well.  Please remove it.
