### ISSUE TITLE
Couldn't look up profile properties for ...

### ISSUE THREAD

**Issue by PanetiX** [GeyserMC/MCProtocolLib#709]
Hey we get this errors: 

[10:40:24] [Profile Lookup Executor #0/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@65dedd5d[id=00000000-0000-0000-0009-01f5dc2c4b8b,name=.Jassi30Lilli,properties={},legacy=false]
java.lang.IllegalArgumentException: Name and ID cannot both be blank
    at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.11.49.jar:?]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:203) ~[authlib-3.11.49.jar:?]
    at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[paper-1.19.2.jar:git-Paper-214]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:175) ~[authlib-3.11.49.jar:?]
    at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[paper-1.19.2.jar:git-Paper-214]
    at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$3(SkullBlockEntity.java:142) ~[?:?]
    at net.minecraft.Util.ifElse(Util.java:467) ~[?:?]
    at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$6(SkullBlockEntity.java:139) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]

Paper 1.19.2 (latest) and Geyser / Floodgate (latest Versions)

**Comment by Camotoy** [comment]
This is the wrong repository. Regardless, we are aware of the issue.

**Comment by PanetiX** [comment]
> This is the wrong repository. Regardless, we are aware of the issue.

and when this will be fixed?
