### ISSUE TITLE
Sound Error?

### ISSUE THREAD

**Issue by chaseking** [GeyserMC/MCProtocolLib#79]
I'm testing a bot using this library on my local server. However, when this specific custom sound is sent, the connection between the bot and my local server crashes, and I get this error. How can I fix this?

``` text
[14:59:20] SOUND > Custom sound: "game.testsounds.battlelost"
[14:59:21] CONNECTION > Disconnected: Internal network exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(1) exceeds writerIndex(9): UnpooledHeapByteBuf(ridx: 9, widx: 9, cap: 9)
[14:59:21] CONNECTION > Logging in again in 10 seconds...
[14:59:31] CONNECTION > Successfully authenticated user.
[14:59:31] CONNECTION > Connecting to local test server...
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(1) exceeds writerIndex(9): UnpooledHeapByteBuf(ridx: 9, widx: 9, cap: 9)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:258)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:140)
    at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:154)
    at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:154)
    at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:154)
    at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:148)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:138)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:317)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.oio.AbstractOioByteChannel.doRead(AbstractOioByteChannel.java:123)
    at io.netty.channel.oio.AbstractOioChannel$1.run(AbstractOioChannel.java:40)
    at io.netty.channel.ThreadPerChannelEventLoop.run(ThreadPerChannelEventLoop.java:38)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(1) exceeds writerIndex(9): UnpooledHeapByteBuf(ridx: 9, widx: 9, cap: 9)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1161)
    at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:563)
    at org.spacehq.packetlib.tcp.io.ByteBufNetInput.readByte(ByteBufNetInput.java:27)
    at org.spacehq.packetlib.tcp.io.ByteBufNetInput.readVarInt(ByteBufNetInput.java:60)
    at org.spacehq.mc.protocol.packet.ingame.server.ServerKeepAlivePacket.read(ServerKeepAlivePacket.java:27)
    at org.spacehq.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:42)
    at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:227)
    ... 30 more
```

**Comment by Steveice10** [comment]
Closing due to age. If you are still having this issue, respond with further details such as the specific packet you're receiving the sound in (I assume ServerPlaySoundPacket, but just in case) and any other packets received between it and the disconnect.

**Comment by andrewgazelka** [comment]
I'm getting a similar issue
https://hastebin.com/usepecabol.sql
